### ISSUE TITLE
Optionally disable scoped styles

### ISSUE THREAD

**Issue by Silind** [Silind-Software/direflow#52]
### Feature
There should be an option to disable scoped styles.

The configuration should be set in the `configure` method:
```javascript
direflowComponent.configure({
  name: 'example-component',
  useShadow: true,
  scopedStyles: false, // <- We disable scoped styles here
});
```
### Result
The unique identifier disappears on css classes and HTML elements:

### Example
```html
// With scoped styles
<div class="app s263677616">
...
// Without scoped styles
<div class="app">
...
```

```css
// With scoped styles
.s263677616 a {
  text-decoration: none; color: inherit; 
}

// Without scoped styles
a {
  text-decoration: none; color: inherit; 
}
```

### Additional context
Currently, the third-party library [style-it](https://github.com/buildbreakdo/style-it) is used for injecting styles. This feature may not be possible with [style-it](https://github.com/buildbreakdo/style-it), so another option for handling styles may be needed.
